use_frameworks!

platform :ios, '9.0'

target 'AZNavigationController_Example' do
  pod 'AZNavigationController', :path => '../'

  target 'AZNavigationController_Tests' do
    inherit! :search_paths

    
  end
end
